var annotated_dup =
[
    [ "dbDate", "_r_e_a_lplugin_8h.html#structdb_date", "_r_e_a_lplugin_8h_structdb_date" ],
    [ "dbTime", "_r_e_a_lplugin_8h.html#structdb_time", "_r_e_a_lplugin_8h_structdb_time" ],
    [ "dbTimeStamp", "_r_e_a_lplugin_8h.html#structdb_time_stamp", "_r_e_a_lplugin_8h_structdb_time_stamp" ],
    [ "REALattribute", "_r_e_a_lplugin_8h.html#struct_r_e_a_lattribute", "_r_e_a_lplugin_8h_struct_r_e_a_lattribute" ],
    [ "REALclassDefinition", "_r_e_a_lplugin_8h.html#struct_r_e_a_lclass_definition", "_r_e_a_lplugin_8h_struct_r_e_a_lclass_definition" ],
    [ "REALcolumnConstraints", "_r_e_a_lplugin_8h.html#struct_r_e_a_lcolumn_constraints", "_r_e_a_lplugin_8h_struct_r_e_a_lcolumn_constraints" ],
    [ "REALcolumnValue", "_r_e_a_lplugin_8h.html#struct_r_e_a_lcolumn_value", "_r_e_a_lplugin_8h_struct_r_e_a_lcolumn_value" ],
    [ "REALconstant", "_r_e_a_lplugin_8h.html#struct_r_e_a_lconstant", "_r_e_a_lplugin_8h_struct_r_e_a_lconstant" ],
    [ "REALcontrol", "_r_e_a_lplugin_8h.html#struct_r_e_a_lcontrol", "_r_e_a_lplugin_8h_struct_r_e_a_lcontrol" ],
    [ "REALcontrolBehaviour", "struct_r_e_a_lcontrol_behaviour.html", "struct_r_e_a_lcontrol_behaviour" ],
    [ "REALcursorUpdate", "_r_e_a_lplugin_8h.html#struct_r_e_a_lcursor_update", "_r_e_a_lplugin_8h_struct_r_e_a_lcursor_update" ],
    [ "REALDatabaseConnectionDefinition", "struct_r_e_a_l_database_connection_definition.html", "struct_r_e_a_l_database_connection_definition" ],
    [ "REALdbCursorDefinition", "struct_r_e_a_ldb_cursor_definition.html", "struct_r_e_a_ldb_cursor_definition" ],
    [ "REALdbEngineDefinition", "struct_r_e_a_ldb_engine_definition.html", "struct_r_e_a_ldb_engine_definition" ],
    [ "REALdbTableDefinition", "_r_e_a_lplugin_8h.html#struct_r_e_a_ldb_table_definition", "_r_e_a_lplugin_8h_struct_r_e_a_ldb_table_definition" ],
    [ "REALdelegate", "_r_e_a_lplugin_8h.html#struct_r_e_a_ldelegate", "_r_e_a_lplugin_8h_struct_r_e_a_ldelegate" ],
    [ "REALenum", "_r_e_a_lplugin_8h.html#struct_r_e_a_lenum", "_r_e_a_lplugin_8h_struct_r_e_a_lenum" ],
    [ "REALevent", "_r_e_a_lplugin_8h.html#struct_r_e_a_levent", "_r_e_a_lplugin_8h_struct_r_e_a_levent" ],
    [ "REALeventInstance", "_r_e_a_lplugin_8h.html#struct_r_e_a_levent_instance", "_r_e_a_lplugin_8h_struct_r_e_a_levent_instance" ],
    [ "REALfieldUpdate", "_r_e_a_lplugin_8h.html#struct_r_e_a_lfield_update", "_r_e_a_lplugin_8h_struct_r_e_a_lfield_update" ],
    [ "REALgetColumn", "_r_e_a_lplugin_8h.html#struct_r_e_a_lget_column", "_r_e_a_lplugin_8h_struct_r_e_a_lget_column" ],
    [ "REALinterfaceDefinition", "_r_e_a_lplugin_8h.html#struct_r_e_a_linterface_definition", "_r_e_a_lplugin_8h_struct_r_e_a_linterface_definition" ],
    [ "REALmethodDefinition", "_r_e_a_lplugin_8h.html#struct_r_e_a_lmethod_definition", "_r_e_a_lplugin_8h_struct_r_e_a_lmethod_definition" ],
    [ "REALmobileControl", "_r_e_a_lplugin_8h.html#struct_r_e_a_lmobile_control", "_r_e_a_lplugin_8h_struct_r_e_a_lmobile_control" ],
    [ "REALmobileControlBehaviour", "struct_r_e_a_lmobile_control_behaviour.html", "struct_r_e_a_lmobile_control_behaviour" ],
    [ "REALmoduleDefinition", "_r_e_a_lplugin_8h.html#struct_r_e_a_lmodule_definition", "_r_e_a_lplugin_8h_struct_r_e_a_lmodule_definition" ],
    [ "REALnewColumn", "_r_e_a_lplugin_8h.html#struct_r_e_a_lnew_column", "_r_e_a_lplugin_8h_struct_r_e_a_lnew_column" ],
    [ "REALpictureDescription", "_r_e_a_lplugin_8h.html#struct_r_e_a_lpicture_description", "_r_e_a_lplugin_8h_struct_r_e_a_lpicture_description" ],
    [ "REALproperty", "_r_e_a_lplugin_8h.html#struct_r_e_a_lproperty", "_r_e_a_lplugin_8h_struct_r_e_a_lproperty" ],
    [ "REALstringData", "_r_e_a_lplugin_8h.html#struct_r_e_a_lstring_data", "_r_e_a_lplugin_8h_struct_r_e_a_lstring_data" ],
    [ "REALstructure", "_r_e_a_lplugin_8h.html#struct_r_e_a_lstructure", "_r_e_a_lplugin_8h_struct_r_e_a_lstructure" ],
    [ "REALtextData", "rb__plugin_8h.html#struct_r_e_a_ltext_data", "rb__plugin_8h_struct_r_e_a_ltext_data" ],
    [ "Rect", "_r_e_a_lplugin_8h.html#struct_rect", "_r_e_a_lplugin_8h_struct_rect" ]
];